baseURL: https://kozymacro.com/
title: Kozy Macro - Knight Online
enableRobotsTXT: true
publishdir: docs
theme: default

googleAnalytics: UA-111573294-1

params:
  version: v2.5.0
  downloadLink: https://storage.googleapis.com/kozy-releases/Kozi-v2.5.0.exe
  downloadLinkMirror1: 
  riseVersion: v2.5.0
  riseDownloadLink: https://storage.googleapis.com/kozy-releases/Kozir-v2.5.0.exe
  betaVersion: 
  betaDownloadLink: 
  showNewFeaturesOnTop: false
  paymentMethod: "stripe"

languages:
  en:
    url: "/"
    contentDir: "content/en"
  tr:
    url: "/tr"
    contentDir: "content/tr"
