baseURL: https://kozymacro.com/
title: Kozy Macro - Knight Online
enableRobotsTXT: true
disableKinds: ["taxonomy", "taxonomyTerm"]
publishdir: docs
theme: default

googleAnalytics: UA-111573294-1

params:
  version: v2.3
  downloadLink: https://github.com/kozymacro/kozymacro/releases/download/2.3.2/Kozy-2.3.2-Installer.zip
  betaVersion: v2.4
  betaDownloadLink: https://github.com/kozymacro/kozymacro/releases/download/2.4.0-beta.2/Kozy-2.4.0-beta.2-Installer.zip
  showNewFeaturesOnTop: true

languages:
  en:
    url: "/"
  tr:
    url: "/tr"
