baseURL: https://kozymacro.com/
title: Kozy Macro - Knight Online
enableRobotsTXT: true
publishdir: docs
theme: default

googleAnalytics: UA-111573294-1

params:
  version: v2.4.8
  downloadLink: https://github.com/kozymacro/web/releases/download/2.4.8/Koz.exe
  downloadLinkMirror1: 
  riseVersion: v2.5.0 beta.8
  riseDownloadLink: https://github.com/kozymacro/web/releases/download/2.5.0-beta.8/Kozi.r.8.exe
  betaVersion: v2.5.0 beta.8
  betaDownloadLink: https://github.com/kozymacro/web/releases/download/2.5.0-beta.8/Kozi.beta.8.exe
  showNewFeaturesOnTop: true
  paymentMethod: "stripe"

languages:
  en:
    url: "/"
    contentDir: "content/en"
  tr:
    url: "/tr"
    contentDir: "content/tr"
