baseURL: https://kozymacro.com/
title: Kozy Macro - Knight Online
enableRobotsTXT: true
publishdir: docs
theme: default

params:
  version: v2.4
  downloadLink: https://github.com/kozymacro/web/releases/download/2.4.4/Kozy-2.4.4-Installer.exe
  betaVersion: 
  betaDownloadLink: 
  showNewFeaturesOnTop: false
  paymentMethod: "stripe"

languages:
  en:
    url: "/"
    contentDir: "content/en"
  tr:
    url: "/tr"
    contentDir: "content/tr"
