baseURL: https://kozymacro.com/
title: Kozy Macro - Knight Online
enableRobotsTXT: true
publishdir: docs
theme: default

googleAnalytics: UA-111573294-1

params:
  version: v2.4.4
  downloadLink: https://github.com/kozymacro/web/releases/download/2.4.4/Kozy-2.4.4-Installer.exe
  betaVersion: v2.4.5
  betaDownloadLink: https://github.com/kozymacro/web/releases/download/2.4.5-beta.4/Kozy-2.4.5-beta.4-Installer.exe
  showNewFeaturesOnTop: false
  paymentMethod: "stripe"

languages:
  en:
    url: "/"
    contentDir: "content/en"
  tr:
    url: "/tr"
    contentDir: "content/tr"
