baseURL: https://kozymacro.com/
title: Kozy Macro - Knight Online
enableRobotsTXT: true
publishdir: docs
theme: default

googleAnalytics: UA-111573294-1

params:
  version: v2.4.8
  downloadLink: https://github.com/kozymacro/web/releases/download/2.4.8/Zet.exe
  downloadLinkMirror1: 
  riseDownloadLink: https://github.com/kozymacro/web/releases/download/2.4.8-beta-rise.2/RO.exe
  betaVersion: 
  betaDownloadLink: 
  showNewFeaturesOnTop: false
  paymentMethod: "stripe"

languages:
  en:
    url: "/"
    contentDir: "content/en"
  tr:
    url: "/tr"
    contentDir: "content/tr"
